<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Forja.Application\Forja.Application.csproj" />
    <ProjectReference Include="..\Forja.Infrastructure\Forja.Infrastructure.csproj" />
    <ProjectReference Include="..\Forja.Infrastructure.Ia\Forja.Infrastructure.Ia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="ScottBrady.IdentityModel" Version="4.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
