// <auto-generated />
using System;
using Forja.Domain.Conteudo;
using Forja.Domain.Contribuicao;
using Forja.Domain.Estudo;
using Forja.Domain.Questoes;
using Forja.Domain.Usuarios;
using Forja.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Forja.Infrastructure.Migrations
{
    [DbContext(typeof(ForjaDbContext))]
    [Migration("20260730200416_CriaContribuicaoReputacao")]
    partial class CriaContribuicaoReputacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "nivel_usuario", new[] { "avancado", "iniciante", "intermediario" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "nivel_usuario", "nivel_usuario", new[] { "iniciante", "intermediario", "avancado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "origem_questao", new[] { "gerada_ia", "inedita", "reproduzida_prova_oficial" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "origem_questao", "origem_questao", new[] { "gerada_ia", "reproduzida_prova_oficial", "inedita" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_contribuicao", new[] { "aprovada", "em_revisao", "rejeitada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_contribuicao", "status_contribuicao", new[] { "em_revisao", "aprovada", "rejeitada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_item_plano", new[] { "concluido", "pendente" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_item_plano", "status_item_plano", new[] { "pendente", "concluido" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_questao", new[] { "aprovada", "em_revisao", "rascunho", "rejeitada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_questao", "status_questao", new[] { "rascunho", "em_revisao", "aprovada", "rejeitada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_contribuicao", new[] { "pdf", "video" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_contribuicao", "tipo_contribuicao", new[] { "video", "pdf" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_fonte", new[] { "edital", "lei", "prova" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_fonte", "tipo_fonte", new[] { "lei", "edital", "prova" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_questao", new[] { "certo_errado", "multipla_escolha" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_questao", "tipo_questao", new[] { "certo_errado", "multipla_escolha" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forja.Domain.Catalogo.Banca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_bancas");

                    b.ToTable("bancas", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Catalogo.Carreira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AtivoNoCatalogo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo_no_catalogo");

                    b.Property<string>("Cargo")
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Orgao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("orgao");

                    b.HasKey("Id")
                        .HasName("pk_carreiras");

                    b.ToTable("carreiras", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Catalogo.Disciplina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_disciplinas");

                    b.ToTable("disciplinas", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Catalogo.Edital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<Guid>("BancaId")
                        .HasColumnType("uuid")
                        .HasColumnName("banca_id");

                    b.Property<Guid>("CarreiraId")
                        .HasColumnType("uuid")
                        .HasColumnName("carreira_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataProva")
                        .HasColumnType("date")
                        .HasColumnName("data_prova");

                    b.Property<string>("UrlFonte")
                        .HasColumnType("text")
                        .HasColumnName("url_fonte");

                    b.HasKey("Id")
                        .HasName("pk_editais");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("ix_editais_banca_id");

                    b.HasIndex("CarreiraId")
                        .HasDatabaseName("ix_editais_carreira_id");

                    b.ToTable("editais", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Catalogo.EditalPesoDisciplina", b =>
                {
                    b.Property<Guid>("EditalId")
                        .HasColumnType("uuid")
                        .HasColumnName("edital_id");

                    b.Property<Guid>("DisciplinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("disciplina_id");

                    b.Property<DateTimeOffset>("CalculadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculado_em");

                    b.Property<Guid?>("EditalOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("edital_origem_id");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fonte");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric")
                        .HasColumnName("peso");

                    b.HasKey("EditalId", "DisciplinaId")
                        .HasName("pk_edital_peso_disciplina");

                    b.HasIndex("DisciplinaId")
                        .HasDatabaseName("ix_edital_peso_disciplina_disciplina_id");

                    b.HasIndex("EditalOrigemId")
                        .HasDatabaseName("ix_edital_peso_disciplina_edital_origem_id");

                    b.ToTable("edital_peso_disciplina", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Catalogo.Topico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DisciplinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("disciplina_id");

                    b.Property<Guid>("EditalId")
                        .HasColumnType("uuid")
                        .HasColumnName("edital_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id")
                        .HasName("pk_topicos");

                    b.HasIndex("DisciplinaId")
                        .HasDatabaseName("ix_topicos_disciplina_id");

                    b.HasIndex("EditalId")
                        .HasDatabaseName("ix_topicos_edital_id");

                    b.ToTable("topicos", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Conteudo.ChunkConteudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector")
                        .HasColumnName("embedding");

                    b.Property<Guid>("FonteId")
                        .HasColumnType("uuid")
                        .HasColumnName("fonte_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<Guid?>("TopicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("topico_id");

                    b.HasKey("Id")
                        .HasName("pk_chunks_conteudo");

                    b.HasIndex("FonteId")
                        .HasDatabaseName("ix_chunks_conteudo_fonte_id");

                    b.HasIndex("TopicoId")
                        .HasDatabaseName("ix_chunks_conteudo_topico_id");

                    b.ToTable("chunks_conteudo", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Conteudo.FonteConteudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CaminhoArquivo")
                        .HasColumnType("text")
                        .HasColumnName("caminho_arquivo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("EditalId")
                        .HasColumnType("uuid")
                        .HasColumnName("edital_id");

                    b.Property<string>("TextoExtraido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto_extraido");

                    b.Property<TipoFonte>("Tipo")
                        .HasColumnType("tipo_fonte")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<DateTimeOffset>("VersaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("versao_em");

                    b.HasKey("Id")
                        .HasName("pk_fontes_conteudo");

                    b.HasIndex("EditalId")
                        .HasDatabaseName("ix_fontes_conteudo_edital_id");

                    b.ToTable("fontes_conteudo", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Contribuicao.ContribuicaoConteudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<DateTimeOffset?>("ModeradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moderado_em");

                    b.Property<Guid?>("ModeradoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("moderado_por");

                    b.Property<StatusContribuicao>("Status")
                        .HasColumnType("status_contribuicao")
                        .HasColumnName("status");

                    b.Property<TipoContribuicao>("Tipo")
                        .HasColumnType("tipo_contribuicao")
                        .HasColumnName("tipo");

                    b.Property<Guid>("TopicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("topico_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_contribuicoes_conteudo");

                    b.HasIndex("ModeradoPor")
                        .HasDatabaseName("ix_contribuicoes_conteudo_moderado_por");

                    b.HasIndex("TopicoId")
                        .HasDatabaseName("ix_contribuicoes_conteudo_topico_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_contribuicoes_conteudo_usuario_id");

                    b.ToTable("contribuicoes_conteudo", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Estudo.PlanoEstudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarreiraId")
                        .HasColumnType("uuid")
                        .HasColumnName("carreira_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("GeradoViaIA")
                        .HasColumnType("boolean")
                        .HasColumnName("gerado_via_ia");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_planos_estudo");

                    b.HasIndex("CarreiraId")
                        .HasDatabaseName("ix_planos_estudo_carreira_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_planos_estudo_usuario_id");

                    b.ToTable("planos_estudo", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Estudo.PlanoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DataPrevista")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<StatusItemPlano>("Status")
                        .HasColumnType("status_item_plano")
                        .HasColumnName("status");

                    b.Property<int>("TempoAlocadoMin")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_alocado_min");

                    b.Property<Guid>("TopicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("topico_id");

                    b.HasKey("Id")
                        .HasName("pk_plano_itens");

                    b.HasIndex("PlanoId")
                        .HasDatabaseName("ix_plano_itens_plano_id");

                    b.HasIndex("TopicoId")
                        .HasDatabaseName("ix_plano_itens_topico_id");

                    b.ToTable("plano_itens", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Estudo.Pomodoro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DuracaoPrevistaMin")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_prevista_min");

                    b.Property<DateTimeOffset?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalizado_em");

                    b.Property<DateTimeOffset>("IniciadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciado_em");

                    b.Property<int>("PontosConcedidos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos_concedidos");

                    b.Property<int>("QtdRespostasNoCiclo")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_respostas_no_ciclo");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_id");

                    b.HasKey("Id")
                        .HasName("pk_pomodoros");

                    b.HasIndex("SessaoId")
                        .HasDatabaseName("ix_pomodoros_sessao_id");

                    b.ToTable("pomodoros", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Estudo.RespostaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Correta")
                        .HasColumnType("boolean")
                        .HasColumnName("correta");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("EhRevisao")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_revisao");

                    b.Property<Guid?>("PomodoroId")
                        .HasColumnType("uuid")
                        .HasColumnName("pomodoro_id");

                    b.Property<int>("PontosConcedidos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos_concedidos");

                    b.Property<bool>("Pontuada")
                        .HasColumnType("boolean")
                        .HasColumnName("pontuada");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("questao_id");

                    b.Property<string>("RespostaDada")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resposta_dada");

                    b.Property<int>("TempoRespostaMs")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_resposta_ms");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_respostas_usuario");

                    b.HasIndex("PomodoroId")
                        .HasDatabaseName("ix_respostas_usuario_pomodoro_id");

                    b.HasIndex("QuestaoId")
                        .HasDatabaseName("ix_respostas_usuario_questao_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_respostas_usuario_usuario_id");

                    b.ToTable("respostas_usuario", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Estudo.RevisaoEspacada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ErrosConsecutivos")
                        .HasColumnType("integer")
                        .HasColumnName("erros_consecutivos");

                    b.Property<int>("IntervaloDiasAtual")
                        .HasColumnType("integer")
                        .HasColumnName("intervalo_dias_atual");

                    b.Property<DateOnly>("ProximaRevisaoEm")
                        .HasColumnType("date")
                        .HasColumnName("proxima_revisao_em");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("questao_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_revisao_espacada");

                    b.HasIndex("QuestaoId")
                        .HasDatabaseName("ix_revisao_espacada_questao_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_revisao_espacada_usuario_id");

                    b.ToTable("revisao_espacada", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Estudo.SessaoEstudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataSessao")
                        .HasColumnType("date")
                        .HasColumnName("data_sessao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_sessoes_estudo");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_sessoes_estudo_usuario_id");

                    b.ToTable("sessoes_estudo", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Gamificacao.Medalha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Criterio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("criterio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_medalhas");

                    b.ToTable("medalhas", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Gamificacao.Pontuacao", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<int>("PontosSemanaAtual")
                        .HasColumnType("integer")
                        .HasColumnName("pontos_semana_atual");

                    b.Property<int>("PontosTotal")
                        .HasColumnType("integer")
                        .HasColumnName("pontos_total");

                    b.Property<DateOnly>("SemanaReferencia")
                        .HasColumnType("date")
                        .HasColumnName("semana_referencia");

                    b.HasKey("UsuarioId")
                        .HasName("pk_pontuacoes");

                    b.ToTable("pontuacoes", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Gamificacao.ReputacaoContribuicao", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<int>("PontosContribuicao")
                        .HasColumnType("integer")
                        .HasColumnName("pontos_contribuicao");

                    b.HasKey("UsuarioId")
                        .HasName("pk_reputacao_contribuicao");

                    b.ToTable("reputacao_contribuicao", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Gamificacao.Streak", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<int>("DiasConsecutivos")
                        .HasColumnType("integer")
                        .HasColumnName("dias_consecutivos");

                    b.Property<DateOnly?>("UltimaAtividadeEm")
                        .HasColumnType("date")
                        .HasColumnName("ultima_atividade_em");

                    b.HasKey("UsuarioId")
                        .HasName("pk_streaks");

                    b.ToTable("streaks", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Gamificacao.UsuarioMedalha", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("MedalhaId")
                        .HasColumnType("uuid")
                        .HasColumnName("medalha_id");

                    b.Property<DateTimeOffset>("ConquistadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("conquistada_em");

                    b.HasKey("UsuarioId", "MedalhaId")
                        .HasName("pk_usuario_medalhas");

                    b.HasIndex("MedalhaId")
                        .HasDatabaseName("ix_usuario_medalhas_medalha_id");

                    b.ToTable("usuario_medalhas", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Questoes.Questao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alternativas")
                        .HasColumnType("jsonb")
                        .HasColumnName("alternativas");

                    b.Property<int?>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<Guid?>("BancaId")
                        .HasColumnType("uuid")
                        .HasColumnName("banca_id");

                    b.Property<Guid>("CarreiraId")
                        .HasColumnType("uuid")
                        .HasColumnName("carreira_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("DisciplinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("disciplina_id");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enunciado");

                    b.Property<string>("Explicacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explicacao");

                    b.Property<Guid?>("FonteProvaId")
                        .HasColumnType("uuid")
                        .HasColumnName("fonte_prova_id");

                    b.PrimitiveCollection<Guid[]>("FontesChunkIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("fontes_chunk_ids");

                    b.Property<string>("Gabarito")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gabarito");

                    b.Property<string>("Orgao")
                        .HasColumnType("text")
                        .HasColumnName("orgao");

                    b.Property<OrigemQuestao>("Origem")
                        .HasColumnType("origem_questao")
                        .HasColumnName("origem");

                    b.Property<DateTimeOffset?>("RevisadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revisado_em");

                    b.Property<Guid?>("RevisadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("revisado_por");

                    b.Property<StatusQuestao>("Status")
                        .HasColumnType("status_questao")
                        .HasColumnName("status");

                    b.Property<TipoQuestao>("Tipo")
                        .HasColumnType("tipo_questao")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("TopicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("topico_id");

                    b.HasKey("Id")
                        .HasName("pk_questoes");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("ix_questoes_banca_id");

                    b.HasIndex("CarreiraId")
                        .HasDatabaseName("ix_questoes_carreira_id");

                    b.HasIndex("DisciplinaId")
                        .HasDatabaseName("ix_questoes_disciplina_id");

                    b.HasIndex("FonteProvaId")
                        .HasDatabaseName("ix_questoes_fonte_prova_id");

                    b.HasIndex("RevisadoPor")
                        .HasDatabaseName("ix_questoes_revisado_por");

                    b.HasIndex("TopicoId")
                        .HasDatabaseName("ix_questoes_topico_id");

                    b.ToTable("questoes", (string)null);
                });

            modelBuilder.Entity("Forja.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FusoHorario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fuso_horario");

                    b.Property<NivelUsuario>("Nivel")
                        .HasColumnType("nivel_usuario")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("TempoDisponivelMinDia")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_disponivel_min_dia");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Forja.Infrastructure.ExternalAuth.NeonAuthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("emailVerified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "neon_auth");
                });

            modelBuilder.Entity("Forja.Domain.Catalogo.Edital", b =>
                {
                    b.HasOne("Forja.Domain.Catalogo.Banca", null)
                        .WithMany()
                        .HasForeignKey("BancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_editais_bancas_banca_id");

                    b.HasOne("Forja.Domain.Catalogo.Carreira", null)
                        .WithMany()
                        .HasForeignKey("CarreiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_editais_carreiras_carreira_id");
                });

            modelBuilder.Entity("Forja.Domain.Catalogo.EditalPesoDisciplina", b =>
                {
                    b.HasOne("Forja.Domain.Catalogo.Disciplina", null)
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edital_peso_disciplina_disciplinas_disciplina_id");

                    b.HasOne("Forja.Domain.Catalogo.Edital", null)
                        .WithMany()
                        .HasForeignKey("EditalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edital_peso_disciplina_editais_edital_id");

                    b.HasOne("Forja.Domain.Catalogo.Edital", null)
                        .WithMany()
                        .HasForeignKey("EditalOrigemId")
                        .HasConstraintName("fk_edital_peso_disciplina_editais_edital_origem_id");
                });

            modelBuilder.Entity("Forja.Domain.Catalogo.Topico", b =>
                {
                    b.HasOne("Forja.Domain.Catalogo.Disciplina", null)
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topicos_disciplinas_disciplina_id");

                    b.HasOne("Forja.Domain.Catalogo.Edital", null)
                        .WithMany()
                        .HasForeignKey("EditalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topicos_editais_edital_id");
                });

            modelBuilder.Entity("Forja.Domain.Conteudo.ChunkConteudo", b =>
                {
                    b.HasOne("Forja.Domain.Conteudo.FonteConteudo", null)
                        .WithMany()
                        .HasForeignKey("FonteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chunks_conteudo_fontes_conteudo_fonte_id");

                    b.HasOne("Forja.Domain.Catalogo.Topico", null)
                        .WithMany()
                        .HasForeignKey("TopicoId")
                        .HasConstraintName("fk_chunks_conteudo_topicos_topico_id");
                });

            modelBuilder.Entity("Forja.Domain.Conteudo.FonteConteudo", b =>
                {
                    b.HasOne("Forja.Domain.Catalogo.Edital", null)
                        .WithMany()
                        .HasForeignKey("EditalId")
                        .HasConstraintName("fk_fontes_conteudo_editais_edital_id");
                });

            modelBuilder.Entity("Forja.Domain.Contribuicao.ContribuicaoConteudo", b =>
                {
                    b.HasOne("Forja.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModeradoPor")
                        .HasConstraintName("fk_contribuicoes_conteudo_usuarios_moderado_por");

                    b.HasOne("Forja.Domain.Catalogo.Topico", null)
                        .WithMany()
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contribuicoes_conteudo_topicos_topico_id");

                    b.HasOne("Forja.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contribuicoes_conteudo_usuarios_usuario_id");
                });

            modelBuilder.Entity("Forja.Domain.Estudo.PlanoEstudo", b =>
                {
                    b.HasOne("Forja.Domain.Catalogo.Carreira", null)
                        .WithMany()
                        .HasForeignKey("CarreiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planos_estudo_carreiras_carreira_id");

                    b.HasOne("Forja.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planos_estudo_usuarios_usuario_id");
                });

            modelBuilder.Entity("Forja.Domain.Estudo.PlanoItem", b =>
                {
                    b.HasOne("Forja.Domain.Estudo.PlanoEstudo", null)
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plano_itens_planos_estudo_plano_id");

                    b.HasOne("Forja.Domain.Catalogo.Topico", null)
                        .WithMany()
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plano_itens_topicos_topico_id");
                });

            modelBuilder.Entity("Forja.Domain.Estudo.Pomodoro", b =>
                {
                    b.HasOne("Forja.Domain.Estudo.SessaoEstudo", null)
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pomodoros_sessoes_estudo_sessao_id");
                });

            modelBuilder.Entity("Forja.Domain.Estudo.RespostaUsuario", b =>
                {
                    b.HasOne("Forja.Domain.Estudo.Pomodoro", null)
                        .WithMany()
                        .HasForeignKey("PomodoroId")
                        .HasConstraintName("fk_respostas_usuario_pomodoros_pomodoro_id");

                    b.HasOne("Forja.Domain.Questoes.Questao", null)
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respostas_usuario_questoes_questao_id");

                    b.HasOne("Forja.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respostas_usuario_usuarios_usuario_id");
                });

            modelBuilder.Entity("Forja.Domain.Estudo.RevisaoEspacada", b =>
                {
                    b.HasOne("Forja.Domain.Questoes.Questao", null)
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_revisao_espacada_questoes_questao_id");

                    b.HasOne("Forja.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_revisao_espacada_usuarios_usuario_id");
                });

            modelBuilder.Entity("Forja.Domain.Estudo.SessaoEstudo", b =>
                {
                    b.HasOne("Forja.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_estudo_usuarios_usuario_id");
                });

            modelBuilder.Entity("Forja.Domain.Gamificacao.UsuarioMedalha", b =>
                {
                    b.HasOne("Forja.Domain.Gamificacao.Medalha", null)
                        .WithMany()
                        .HasForeignKey("MedalhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_medalhas_medalhas_medalha_id");

                    b.HasOne("Forja.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_medalhas_usuarios_usuario_id");
                });

            modelBuilder.Entity("Forja.Domain.Questoes.Questao", b =>
                {
                    b.HasOne("Forja.Domain.Catalogo.Banca", null)
                        .WithMany()
                        .HasForeignKey("BancaId")
                        .HasConstraintName("fk_questoes_bancas_banca_id");

                    b.HasOne("Forja.Domain.Catalogo.Carreira", null)
                        .WithMany()
                        .HasForeignKey("CarreiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questoes_carreiras_carreira_id");

                    b.HasOne("Forja.Domain.Catalogo.Disciplina", null)
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questoes_disciplinas_disciplina_id");

                    b.HasOne("Forja.Domain.Conteudo.FonteConteudo", null)
                        .WithMany()
                        .HasForeignKey("FonteProvaId")
                        .HasConstraintName("fk_questoes_fontes_conteudo_fonte_prova_id");

                    b.HasOne("Forja.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("RevisadoPor")
                        .HasConstraintName("fk_questoes_usuarios_revisado_por");

                    b.HasOne("Forja.Domain.Catalogo.Topico", null)
                        .WithMany()
                        .HasForeignKey("TopicoId")
                        .HasConstraintName("fk_questoes_topicos_topico_id");
                });
#pragma warning restore 612, 618
        }
    }
}
